Практична робота №1. Варіант 12. Мішакін І. І. 4-5

Створіть одновимірний масив (вектор) зі зменшувальною арифметичною послідовністю, де кожне наступне число менше попереднього на 4, 
починаючи з 50, та виведіть його значення. 

In [3]:
import numpy as np

In [22]:
start = 50
step = -4
count = 10

sequence = np.arange(start, start + count * step, step)
sequence

array([50, 46, 42, 38, 34, 30, 26, 22, 18, 14])

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями суми добутків кожного числа на його попереднє, 
починаючи з 1, та виведіть його значення. 

In [21]:
rows = 3
cols = 3

matrix = np.zeros((rows, cols), dtype=int)
matrix[0, 0] = 1
matrix[0, 1] = 2
for i in range(rows):
    for j in range(cols):
        if matrix[i, j] != 0:
            continue
        if j == 2:
            matrix[i, j] = matrix[i, j - 1] * (matrix[i, j - 2])
        elif j == 1:
            matrix[i, j] = matrix[i, j - 1] * (matrix[i - 1, j + 1])
        elif j == 0:
            matrix[i, j] = matrix[i - 1, 2] * (matrix[i - 1, 1])
        
matrix

array([[      1,       2,       2],
       [      4,       8,      32],
       [    256,    8192, 2097152]])

Створіть масив розміром 9x9, заповніть його випадковими цілими числами в діапазоні від -100 до 100 та знайдіть мінімальний елемент. 

In [26]:
matrix = np.random.randint(-100, 101, (9, 9))
min_element = np.min(matrix)
min_element

-97

Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та обчисліть добуток елементів, що менше 0.2. 

In [30]:
matrix = np.random.rand(6, 6)
elements_less_than_0_2 = matrix[matrix < 0.2]
product = np.prod(elements_less_than_0_2)
product

3.9528262431563394e-10

Створіть два одновимірних масиви розміром 4, заповніть їх випадковими дійсними числами від 0 до 1 та виконайте на них поелементні 
операції додавання, віднімання та множення. 

In [31]:
array1 = np.random.rand(4)
array2 = np.random.rand(4)

result_addition = array1 + array2

result_subtraction = array1 - array2

result_multiplication = array1 * array2

print("Додавання:")
print(result_addition)
print("Віднімання:")
print(result_subtraction)
print("Множення:")
print(result_multiplication)


Додавання:
[1.65316168 1.1334198  0.93249844 0.96772803]
Віднімання:
[-0.12017094  0.42361644 -0.0404351  -0.66848466]
Множення:
[0.67962562 0.27629739 0.21697959 0.12240645]


Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток. 

In [32]:
vector1 = np.array([1.5, 2.0, 3.5, 4.0])
vector2 = np.array([0.5, 1.0, 1.5, 2.0])

scalar_product = np.dot(vector1, vector2)
scalar_product


16.0

Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою. 

In [33]:
matrix1 = np.random.randint(1, 11, size=(2, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3)) 

result_matrix = np.dot(matrix1, matrix2)
result_matrix


array([[126, 164, 120],
       [ 37,  74,  47]])

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю. 

In [34]:
matrix = np.random.randint(1, 9, size=(3, 3))

print("Початкова матриця (3x3):\n", matrix)

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Обернена матриця:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не має оберненої матриці, оскільки вона не є квадратною або її визначник дорівнює 0.")


Початкова матриця (3x3):
 [[4 7 8]
 [7 8 5]
 [8 4 1]]
Обернена матриця:
 [[ 0.11428571 -0.23809524  0.27619048]
 [-0.31428571  0.57142857 -0.34285714]
 [ 0.34285714 -0.38095238  0.16190476]]


Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в діапазоні від 50 до 100 та транспонуйте її. 

In [35]:
matrix = np.random.uniform(50, 100, size=(8, 8))

print("Початкова матриця:\n", matrix)
print("Транспонована матриця:\n", matrix.T)


Початкова матриця:
 [[79.75135391 69.61043786 51.64115584 59.72860419 63.56580312 51.72373767
  73.11514056 98.54800133]
 [76.34599998 95.40915522 85.1298022  66.09507305 51.34771199 60.0433106
  73.12525246 64.69383992]
 [95.01518056 50.64179124 51.11722531 78.04951731 94.15793194 69.07979888
  87.66721893 56.90297786]
 [89.28151463 59.64431568 57.14987987 65.71342396 84.61553369 91.06801012
  57.73449044 74.14375032]
 [63.4282495  82.02689911 93.54001688 57.17009933 99.60989788 98.26852052
  87.58465044 57.49057189]
 [50.89892246 89.45985543 50.67878316 65.91968458 56.53447966 83.21495156
  76.47880876 64.75233   ]
 [75.79895082 77.73079751 70.29130088 57.21391742 68.75054485 74.66060898
  95.13126128 99.17208843]
 [60.69260339 57.34049702 53.08989482 85.65690764 64.58190857 65.06051864
  68.51037458 81.07925851]]
Транспонована матриця:
 [[79.75135391 76.34599998 95.01518056 89.28151463 63.4282495  50.89892246
  75.79895082 60.69260339]
 [69.61043786 95.40915522 50.64179124 59.644315

Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть суму додатних елементів отриманого вектору. 

In [37]:
matrix = np.random.rand(3, 4)
vector = np.random.randint(1, 11, size=4)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)
print("Сума:", np.sum(vector[vector > 0]))


Матриця:
 [[0.35720244 0.14446946 0.06082187 0.48761762]
 [0.41286751 0.6613562  0.83742734 0.009698  ]
 [0.8955082  0.37606653 0.0897288  0.89401431]]
Вектор:
 [8 7 6 1]
Сума: 22


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів матриці, які більше середнього значення матриці. 

In [38]:
matrix = np.random.randint(1, 11, size=(2, 3))
vector = np.random.rand(3)

print("Матриця:\n", matrix)
print("Вектор:\n", vector)

average_matrix_value = np.mean(matrix)
sum_above_average = np.sum(matrix[matrix > average_matrix_value])

print("Середнє значення матриці:", average_matrix_value)
print("Сума елементів матриці, які більше середнього:", sum_above_average)


Матриця:
 [[ 5  6 10]
 [ 9  2  6]]
Вектор:
 [0.60472443 0.20923381 0.67011097]
Середнє значення матриці: 6.333333333333333
Сума елементів матриці, які більше середнього: 19


Створіть дві матриці розміром 5x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення всіх елементів першої матриці до відповідних елементів другої матриці (поелементне ділення). 

In [39]:
matrix1 = np.random.randint(1, 11, size=(5, 5))
matrix2 = np.random.randint(1, 11, size=(5, 5))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Результат:\n", np.divide(matrix1, matrix2))


Перша матриця:
 [[ 2  8  6  8  1]
 [ 3  5  4  3  5]
 [ 2  1  8  6  3]
 [ 6 10  6  5  2]
 [10  8  6 10  9]]
Друга матриця:
 [[ 4  1  3  6  4]
 [ 5  5  6  9  1]
 [ 4  6  2 10  8]
 [ 4  4  4  9  7]
 [ 1  6  4  5  4]]
Результат:
 [[ 0.5         8.          2.          1.33333333  0.25      ]
 [ 0.6         1.          0.66666667  0.33333333  5.        ]
 [ 0.5         0.16666667  4.          0.6         0.375     ]
 [ 1.5         2.5         1.5         0.55555556  0.28571429]
 [10.          1.33333333  1.5         2.          2.25      ]]


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від -10 до 10 та знайдіть різницю їх елементів. 

In [40]:
matrix1 = np.random.randint(-10, 11, size=(4, 4))
matrix2 = np.random.randint(-10, 11, size=(4, 4))

print("Перша матриця:\n", matrix1)
print("Друга матриця:\n", matrix2)
print("Результат (різниця між елементами матриць):\n", matrix1 - matrix2)


Перша матриця:
 [[ -5  -1  -8   6]
 [ -3   9   2   1]
 [  0 -10  -9   1]
 [ -2  -9   5   0]]
Друга матриця:
 [[ 10  -9  -5 -10]
 [  4   0   8   4]
 [  3   3   7  -2]
 [  4  -5   0   7]]
Результат (різниця між елементами матриць):
 [[-15   8  -3  16]
 [ -7   9  -6  -3]
 [ -3 -13 -16   3]
 [ -6  -4   5  -7]]


Створіть матрицю розміром 10x10, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці, які менше за їх середнє арифметичне значення. 

In [41]:
matrix = np.random.randint(1, 101, size=(10, 10))
print("матриця:\n", matrix)
average_value = np.mean(matrix)
sum_below_average = np.sum(matrix[matrix < average_value])

print("Середнє арифметичне значення елементів матриці:", average_value)
print("Сума елементів, які менше за середнє арифметичне значення:", sum_below_average)


матриця:
 [[ 63  35  46   6  69  58  72  99  47  91]
 [ 71  81  94  30  76  32  70  19  84  92]
 [  4  13  80 100  95   7  38  95   4  12]
 [ 39  49  26  88  64  44  91 100  44  72]
 [ 79  53  29  99  92 100  93  12  73   8]
 [ 72  44  24  96  97  63  45  62  11   7]
 [ 23  37  82  76  80  90  50  33  22   2]
 [ 71  69  13  84  29  99  97  83  88  67]
 [ 13  58 100  49  11  38  68  84  25  24]
 [ 52 100  94  18  84  55   2  13  69  44]]
Середнє арифметичне значення елементів матриці: 56.55
Сума елементів, які менше за середнє арифметичне значення: 1281


Створіть матрицю розміром 6x6, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить середнє гармонічне значення елементів кожного рядка матриці. 

In [42]:
matrix = np.random.uniform(-2, 2, size=(6, 6))
print("матриця:\n", matrix)

def harmonic_mean(arr):
    return len(arr) / np.sum(1.0 / arr)

harmonic_means_vector = np.apply_along_axis(harmonic_mean, axis=1, arr=matrix)

print("результат:\n", harmonic_means_vector)


матриця:
 [[ 1.45166787  1.63518403  0.54557991  1.0648365   1.32237401 -0.78536231]
 [-1.93407415  0.7980382  -0.24597285 -1.53370696  0.56366342  0.06381167]
 [ 0.56292601 -1.69583609  1.09988737 -1.99904407  1.96859612 -1.11742476]
 [ 1.70921044 -0.99654402  0.28767076 -1.3317527  -1.97403015 -0.4548065 ]
 [ 0.34638685 -0.02510611  1.00375077  0.5599896  -0.80256197  1.13536469]
 [ 0.63792432 -0.88499081  0.76931601 -1.17770254  0.80247973  1.12527065]]
результат:
 [  1.68759463   0.44564115   4.96376841 -15.05980228  -0.17377592
   1.98466094]
